<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\shared\backend\ObeAunQa.SharedKernel.csproj" />
    <ProjectReference Include="..\..\modules\common\curriculum\backend\ObeAunQa.Modules.Curriculum.csproj" />
    <ProjectReference Include="..\..\modules\sv4\accreditation\backend\ObeAunQa.Modules.Accreditation.csproj" />
    <ProjectReference Include="..\..\modules\sv5\reporting\backend\ObeAunQa.Modules.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
